export const PLATFORM_ROLES = ['PLATFORM_OWNER', 'PLATFORM_ADMIN'];

export const TENANT_ROLES = [
  'TENANT_OWNER',
  'TENANT_ADMIN',
  'EVENT_MANAGER',
  'FINANCE_VIEWER',
  'CHECKIN_STAFF',
];

export const ALL_ROLES = [...PLATFORM_ROLES, ...TENANT_ROLES, 'CUSTOMER'];

export const TENANT_STATUS = ['PENDING_VERIFICATION', 'ACTIVE', 'SUSPENDED', 'INACTIVE'];
export const SUBSCRIPTION_PLANS = ['FREE', 'STARTER', 'BUSINESS', 'ENTERPRISE'];

export const EVENT_STATUS = ['DRAFT', 'LIVE', 'CLOSED', 'CANCELLED'];
export const ACTIVITY_STATUS = ['DRAFT', 'PUBLISHED', 'CLOSED', 'CANCELLED'];

export const REGISTRATION_STATUS = [
  'PENDING',
  'PAYMENT_PENDING',
  'CONFIRMED',
  'CANCELLED',
  'REFUNDED',
  'EXPIRED',
];

export const ORDER_STATUS = ['CREATED', 'PAYMENT_PENDING', 'PAID', 'FAILED', 'CANCELLED', 'REFUNDED'];

export const PAYMENT_STATUS = ['CREATED', 'PENDING', 'AUTHORIZED', 'CAPTURED', 'FAILED', 'REFUNDED'];

export const TICKET_STATUS = ['ACTIVE', 'USED', 'CANCELLED', 'EXPIRED'];

export const FORM_FIELD_TYPES = [
  'TEXT',
  'EMAIL',
  'PHONE',
  'NUMBER',
  'SELECT',
  'RADIO',
  'CHECKBOX',
  'TEXTAREA',
  'DATE',
  'FILE',
  'MULTISELECT',
  'LONGTEXT',
];

export const OTP_PURPOSE = ['CUSTOMER_LOGIN', 'PASSWORD_RESET'];

// Order/registration records older than this are considered abandoned.
export const ORDER_EXPIRY_MINUTES = 30;

export const AUDIT_ACTIONS = {
  TENANT_REGISTERED: 'TENANT_REGISTERED',
  TENANT_STATUS_CHANGED: 'TENANT_STATUS_CHANGED',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  USER_LOGGED_OUT: 'USER_LOGGED_OUT',
  PASSWORD_RESET: 'PASSWORD_RESET',
  EVENT_CREATED: 'EVENT_CREATED',
  EVENT_UPDATED: 'EVENT_UPDATED',
  EVENT_DELETED: 'EVENT_DELETED',
  EVENT_STATUS_CHANGED: 'EVENT_STATUS_CHANGED',
  ACTIVITY_CREATED: 'ACTIVITY_CREATED',
  ACTIVITY_UPDATED: 'ACTIVITY_UPDATED',
  ACTIVITY_DELETED: 'ACTIVITY_DELETED',
  ACTIVITY_STATUS_CHANGED: 'ACTIVITY_STATUS_CHANGED',
  MEMBER_ADDED: 'MEMBER_ADDED',
  MEMBER_UPDATED: 'MEMBER_UPDATED',
  MEMBER_REMOVED: 'MEMBER_REMOVED',
  BOOKING_INITIATED: 'BOOKING_INITIATED',
  PAYMENT_CAPTURED: 'PAYMENT_CAPTURED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  TICKETS_GENERATED: 'TICKETS_GENERATED',
  TICKET_VERIFIED: 'TICKET_VERIFIED',
  TICKET_CHECKED_IN: 'TICKET_CHECKED_IN',
  CHECKIN_REJECTED: 'CHECKIN_REJECTED',
  OTP_REQUESTED: 'OTP_REQUESTED',
};

export default {
  PLATFORM_ROLES,
  TENANT_ROLES,
  ALL_ROLES,
  TENANT_STATUS,
  SUBSCRIPTION_PLANS,
  EVENT_STATUS,
  ACTIVITY_STATUS,
  REGISTRATION_STATUS,
  ORDER_STATUS,
  PAYMENT_STATUS,
  TICKET_STATUS,
  FORM_FIELD_TYPES,
  OTP_PURPOSE,
  ORDER_EXPIRY_MINUTES,
  AUDIT_ACTIONS,
};
